# Generated by Django 3.0 on 2021-01-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='file',
            field=models.ImageField(upload_to='questions'),
        ),
    ]
