# Generated by Django 3.0 on 2021-01-04 06:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210104_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
